First try
VeronikaRevjakina/Notebook pull request #1
Opened 2019-02-24 14:50 UTC by VeronikaRevjakina

I'm not sure about expanding & change methods.

2019-02-26 10:50 UTC, AnnaS91 requested changes

2019-02-26 10:50 UTC, AnnaS91 commented on src/Note.java
> +    Note(){
1) а почему конструктор имеет дефолтный модификатор доступа?
2) можно было бы вызвать this(0, "", "");

2019-02-26 10:50 UTC, AnnaS91 commented on src/Note.java
> +    public int getNoteId(Note note){
замечание ко всем методам get в вашем классе: несколько странно писать внутри класса метод get, который требует передачи ему экземпляра. Т.е. чтобы узнать id какого-то note, вам нужно создать ещё один note, для которого вы будете вызывать метод, что очень нелогично. У вас же в классе уже есть ссылка на текущий экземпляр, поэтому Вы можете просто возвращать id

2019-02-26 10:50 UTC, AnnaS91 commented on src/Note.java
> +        System.out.println( this.toString());
в System.out.println можно просто передавать объект( System.out.println(this) ) , метод toString будет вызван внутри

2019-02-26 10:50 UTC, AnnaS91 commented on src/Note.java
> +    public Note setNoteId(int id){
методы set обычно ничего не возвращают

2019-02-26 10:50 UTC, AnnaS91 commented on src/Note.java
> +        return "id: "+id+" title: "+title+" context: "+context;
конкатенация - довольно дорогая операция. Лучше использовать StringBuilder или String.format

2019-02-26 10:50 UTC, AnnaS91 commented on src/Notebook.java
> +    public static final int initialSize=2;
1. Константы принято именовать заглавными буквами INITIAL_SIZE
2. Скорее всего в Ваш блокнот будут явно добавлять больше 2-х записей, так что лучше задать сразу размер чуть больше

2019-02-26 10:50 UTC, AnnaS91 commented on src/Notebook.java
> +        for(Note i:notesIn){
не используйте однобуквенные имена для переменных, это делает код нечитаемым

2019-02-26 10:50 UTC, AnnaS91 commented on src/Notebook.java
> +        else {
else обычно пишут на той же строке, где закрывается скобка

2019-02-26 10:50 UTC, AnnaS91 commented on src/Notebook.java
> +            for (int i = 0; i < last; i++) {
можно воспользоваться System.arraycopy

2019-02-26 10:50 UTC, AnnaS91 commented on src/Notebook.java
> +            tempNotes[last] = note;
эти две строчки кода повторяются дважды. Логичнее было провести инвертированную проверку, в случае надобности расширить метод (код для этого можно вынести в отдельный private метод), а потом в любом случае добавить элемент и увеличить индекс

2019-02-26 10:50 UTC, AnnaS91 commented on src/Notebook.java
> +    void deleteNote() {
а что если я хочу удалить note c индексом, а не последний?

2019-02-26 10:50 UTC, AnnaS91 commented on src/Notebook.java
> +public class Notebook {
почему у всех методов класса пакетный доступ?

2019-02-26 10:50 UTC, AnnaS91 commented on src/Notebook.java
> +        if(count <= last) {
что будет если передам отрицательное число?

2019-02-26 10:50 UTC, AnnaS91 commented on src/Notebook.java
> +        System.out.println( new Note().toString());
несколько странно создавать и возвращать новый Note, стоило бы сказать наверх, что метод вызван с неправильным индексом

2019-02-26 10:50 UTC, AnnaS91 commented on src/Notebook.java
> +    Note getNoteByCount(int count){
почему count, а не id?

2019-02-26 10:50 UTC, AnnaS91 commented on src/Notebook.java
> +        for(int i=0;i<this.notes.length;i++){
у Вас же хранится last, почему бы не упростить реализацию с его помощью?

2019-02-26 10:50 UTC, AnnaS91 commented on src/Notebook.java
> +            System.out.println( this.notes[i].toString());
toString не нужен, будет вызван автоматически

2019-03-10 12:11 UTC, AnnaS91 requested changes

2019-03-10 12:11 UTC, AnnaS91 commented on src/Notebook.java
> +        }
а разве не нужно обновить last при таком способе создания блокнота?

2019-03-10 12:11 UTC, AnnaS91 commented on src/Notebook.java
> +            this.notes = tempNotes;
а почему сразу не присвоить notes результат работы метода?

2019-03-10 12:11 UTC, AnnaS91 commented on src/Notebook.java
> +            last--;
смотри, last -- ты делаешь в любом случае и проверка тоже идёт с -1, так почему бы это действие не сделать перед циклом. В данном случае это всего одна строка, поэтому выигрыш не так заметен, но если бы это был блок, было бы гораздо логичнее прописать и выполнить его только раз

2019-03-10 12:11 UTC, AnnaS91 commented on src/Notebook.java
> +        this.getNoteById(id); //check if this note exist
1) комментарии принято писать над строкой, к которой они относятся
2) может быть стоит добавить отдельный метод для проверки

2019-03-10 12:11 UTC, AnnaS91 commented on src/Notebook.java
> +
а почему здесь не сужаете массив?

2019-03-10 12:11 UTC, AnnaS91 commented on src/Notebook.java
> +       /*for (int i = 0; i < last; i++) {
так как у вас массив может менять свой размер и быть из одной записи, возможно это решение лучше

2019-03-10 12:11 UTC, AnnaS91 commented on src/Main.java
> +        Note[] notes1={note1,note2};
а почему не попробовали сюда добавить и удалить эл-ты?

2019-03-10 12:11 UTC, AnnaS91 commented on src/Main.java
> +
1. как на счёт проверки отрицательных кейсов - удаления несуществующей записи, редактирования записи с отрицательным индексом и т.д.
2. Надо проверить, что расширение и сужения отрабатывают корректно - добавить в цикле множество записей, проверить что в блокноте, удалить в массиве, проверить, что блокнот уменьшился в размере

2019-03-10 12:21 UTC, VeronikaRevjakina commented on src/Notebook.java
> +       /*for (int i = 0; i < last; i++) {
Цикл лучше? Вы же мне сказали выше использовать copy.

2019-03-10 12:23 UTC, AnnaS91 commented on src/Notebook.java
> +       /*for (int i = 0; i < last; i++) {
я упустила, что есть возможность создавать блокнот из готового массива, что означает возможность получить блокнот размером 1

2019-03-10 12:23 UTC, VeronikaRevjakina commented on src/Notebook.java
> +        }
В методе addNote обновляется last,либо 0 так и останется.

2019-03-10 12:32 UTC, VeronikaRevjakina commented on src/Notebook.java
> +
Не знаю как,потому что если из середины удаляется элемент,а в конце они ещё есть.не понимаю как сокращать длину.

2019-03-10 12:32 UTC, VeronikaRevjakina commented on src/Notebook.java
> +        this.getNoteById(id); //check if this note exist
Добавила,хотя он практически повторяет getNoteById.

2019-03-10 12:38 UTC, AnnaS91 commented on src/Notebook.java
> +
Что значит в конце они есть? У вас же есть индекс last, в зависимости от него и стоит проверять условие

2019-03-12 20:48 UTC, AnnaS91 commented on src/Notebook.java
> +        else{
else на той же строке, что и закрывающаяся скобка

2019-03-12 20:49 UTC, AnnaS91 approved these changes
Задание зачтено!

2019-03-12 21:02 UTC, merged